version: "3.8"

services:

  php-apache:
    build:
      args:
        - WWW_USER_ID=${WWW_USER_ID}
        - WWW_GROUP_ID=${WWW_GROUP_ID}
    ports:
      - ${WEB_PORT}:80
    volumes:
      - ${PROJECT_PATH_HOST}:/var/www/html
  db:
    platform: linux/amd64
    image: mysql:8.0
    volumes:
      - performance-db-strage:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./script:/script
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: study
      MYSQL_HOST: ""
    restart: always
    ports:
      - ${DB_PORT}:3306

volumes:
  performance-db-strage:
